"""Server-rendered UI route — serves the recruiter scan page."""
from __future__ import annotations

import io
import json
import zipfile
from pathlib import Path

from fastapi import APIRouter, HTTPException, Request
from fastapi.responses import HTMLResponse, StreamingResponse

from fastapi.templating import Jinja2Templates

router = APIRouter()

templates_dir = Path(__file__).parent.parent / "templates"
templates = Jinja2Templates(directory=str(templates_dir))

# chrome-extension/ lives at the repo root, two levels up from app/routes/.
_EXTENSION_DIR = Path(__file__).parent.parent.parent / "chrome-extension"


def _extension_version() -> str:
    try:
        return json.loads((_EXTENSION_DIR / "manifest.json").read_text()).get("version", "0.0.0")
    except Exception:  # noqa: BLE001
        return "0.0.0"


@router.get("/", response_class=HTMLResponse)
def index(request: Request) -> HTMLResponse:
    # Starlette ≥0.27 expects (request, name, context) positionally; the older
    # (name, context_with_request) form raises "unhashable type: 'dict'".
    return templates.TemplateResponse(
        request, "index.html",
        {"title": "Auto Screener", "extensionVersion": _extension_version()},
    )


@router.get("/extension.zip")
def extension_zip(request: Request) -> StreamingResponse:
    """Zip up the chrome-extension/ folder so recruiters can install via
    Load Unpacked without cloning the repo.

    At zip-creation time we overwrite `_token.js` with the live
    SCREENER_API_TOKEN + backend URL so the downloaded extension is
    pre-configured — no manual token paste required.
    """
    from ..config import settings
    if not _EXTENSION_DIR.is_dir():
        raise HTTPException(500, "chrome-extension folder not found on server")

    # Backend URL the extension should call — derived from the request the
    # browser made, so it works whether the user is on the production
    # Render URL, a preview, or localhost.
    backend_url = str(request.base_url).rstrip("/")
    embedded_token = (settings.screener_api_token or "").strip()
    token_js_content = (
        '// Generated by /extension.zip — backend embeds the live token here.\n'
        f'window.AS_EMBEDDED_BACKEND = {_js_str(backend_url)};\n'
        f'window.AS_EMBEDDED_TOKEN = {_js_str(embedded_token)};\n'
    )

    buf = io.BytesIO()
    with zipfile.ZipFile(buf, mode="w", compression=zipfile.ZIP_DEFLATED) as zf:
        for path in _EXTENSION_DIR.rglob("*"):
            if not path.is_file() or ".DS_Store" in path.name:
                continue
            rel = str(path.relative_to(_EXTENSION_DIR))
            if rel == "_token.js":
                # Skip the repo placeholder; we'll write the generated one below.
                continue
            zf.write(path, arcname=rel)
        zf.writestr("_token.js", token_js_content)
    buf.seek(0)
    version = _extension_version()
    return StreamingResponse(
        buf,
        media_type="application/zip",
        headers={"Content-Disposition": f'attachment; filename="auto-screener-extension-{version}.zip"'},
    )


def _js_str(s: str) -> str:
    """Escape a Python string for safe embedding as a JS string literal."""
    return json.dumps(s, ensure_ascii=False)


@router.get("/extension/version")
def extension_version() -> dict:
    """Plain-JSON helper the popup or page-side detection JS can hit to compare
    against the running extension's manifest version."""
    return {"version": _extension_version()}
